"""Closed, server-owned event taxonomies."""

from enum import StrEnum


class EventType(StrEnum):
    CUSTOMER_REQUEST = "CUSTOMER_REQUEST"
    CUSTOMER_MESSAGE = "CUSTOMER_MESSAGE"
    CUSTOMER_CREATED = "CUSTOMER_CREATED"
    CUSTOMER_UPDATED = "CUSTOMER_UPDATED"
    ORDER_CREATED = "ORDER_CREATED"
    ORDER_UPDATED = "ORDER_UPDATED"
    PAYMENT_RECEIVED = "PAYMENT_RECEIVED"
    SUPPORT_REQUEST = "SUPPORT_REQUEST"
    INTERNAL_TASK = "INTERNAL_TASK"
    SYSTEM_ALERT = "SYSTEM_ALERT"


class EventSource(StrEnum):
    WEB_FORM = "WEB_FORM"
    API = "API"
    WEBHOOK = "WEBHOOK"
    IMPORT = "IMPORT"
    INTERNAL = "INTERNAL"


class EventCategory(StrEnum):
    CUSTOMER = "CUSTOMER"
    COMMERCE = "COMMERCE"
    SUPPORT = "SUPPORT"
    INTERNAL = "INTERNAL"
    SYSTEM = "SYSTEM"
